version: '3.4'
name: FiapUsers
services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    container_name: FiapUsers
    build:
      context: .
      dockerfile: src/Users.Api/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5000:80"
    networks:
      - postech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  postech-network:
    external: true